図鑑機能の実装
Hakondate/Hakondate pull request #114
Opened 2023-04-01 15:29 UTC by b1017173

**Issueリンク**

#

**実装したこと**

- hoge

**実装しなかったこと**

- 特になし

**スクリーンショット**

**補足事項**

- 特になし

**セルフレビュー**

- [ ] コーディング規約に沿ったコードを書いた
    - ファイル末尾の改行
    - Widgetの階層構造
    - 静的型付け
    くらいは少なくとも確認する
- [ ] 提出予定のファイルを確認し不要な変更やファイルが混入していないかを確認した

2023-05-05 07:36 UTC, mic4dy commented
検索機能以外はできた気がする

2023-05-24 12:33 UTC, Atori-Ikeyama reviewed
Developの最新の差分を取り込んで欲しいです！

2023-07-06 13:41 UTC, Atori-Ikeyama requested changes

2023-07-07 14:22 UTC, mic4dy commented
@Atori-Ikeyama 
修正完了〜

2023-07-07 14:23 UTC, mic4dy commented
↑今後はこのRerequestで修正完了したってことにするわね

2023-07-08 08:19 UTC, Atori-Ikeyama requested changes

2023-07-08 08:19 UTC, Atori-Ikeyama commented on lib/view/dictionary/dictionary_item.dart
> +                ),
```suggestion
                ),
                Divider(
                  color: AppColor.brand.secondaryLight,
                  height: 0,
                ),
```

2023-07-08 08:19 UTC, Atori-Ikeyama commented on lib/view/dictionary/dictionary_item.dart
> +          body: SingleChildScrollView(
![dictionary_item](https://github.com/Hakondate/Hakondate/assets/49859718/809d443e-e901-44d7-9966-622702b579cc)
備考がない時，いたがキチキチになってしまっているので，SafeAreaなどで囲った方が見やすいかもしれないです．

2023-07-08 08:19 UTC, Atori-Ikeyama commented on lib/view_model/single_page/daily/daily_view_model.dart
> +    // final AsyncValue<DailyState> store = state;
このコメントは削除していいと思います

2023-07-08 11:10 UTC, mic4dy commented on lib/view/dictionary/dictionary_item.dart
> +          body: SingleChildScrollView(
完全に忘れてた！ありがとう！

2023-07-10 04:50 UTC, Atori-Ikeyama approved these changes
![LGTM](https://github.com/Hakondate/Hakondate/assets/49859718/b28f9d2e-50e2-4366-a447-faba6f5f7da1)

2023-07-10 11:53 UTC, merged