Feature/user settings
Hakondate/Hakondate pull request #117
Opened 2023-05-24 12:44 UTC by Atori-Ikeyama

**Issueリンク**

#

**実装したこと**

- 

**実装しなかったこと**

- 特になし

**スクリーンショット**

**補足事項**

- 特になし

**セルフレビュー**

- [ ] コーディング規約に沿ったコードを書いた
    - ファイル末尾の改行
    - Widgetの階層構造
    - 静的型付け
    くらいは少なくとも確認する
- [ ] 提出予定のファイルを確認し不要な変更やファイルが混入していないかを確認した

2023-07-08 13:47 UTC, Atori-Ikeyama commented
## Familyを使う際のメモ
オプショナルな引数の場合，引数の数が変わると再ビルドされる．
それはref.read()にも当てはまる．

2023-11-21 08:06 UTC, mic4dy approved these changes
まだ見てる途中なんだけど時間かかりそうだから一旦出しとくわ

2023-12-28 13:39 UTC, mic4dy requested changes
一通り見ました〜

2023-12-28 13:39 UTC, mic4dy commented on lib/view_model/multi_page/user/user_view_model.dart
> +
ここにこのコードがある意味が理解できないかも。
user_view_modelはサービス全体で使うProviderなのでリポジトリ以外の特定のProviderには依存したくない。
アップデートをしたいなら、この関数の呼び出しもとで直後に書くのが良さそう。

2023-12-28 13:39 UTC, mic4dy commented on lib/view_model/multi_page/user/user_view_model.dart
> +    await ref.read(userSettingsViewModelProvider.notifier).updateUsers();
ここも依存は消したい。

2023-12-28 13:39 UTC, mic4dy commented on lib/view_model/single_page/signup/signup_view_model.dart
> +    }
直代入するよりも、各パラメータを更新する関数をそのまま使ったほうがメンテナンスコストが低くなりそう。
この仕様だと、アップデートロジックを変えた時にここまで変える必要がある。
`updateName` `updateSchool` `updateSchoolYear`を使うべきかな。

2023-12-28 13:39 UTC, mic4dy commented on lib/view_model/single_page/signup/signup_view_model.dart
> -  late final SchoolsLocalRepositoryAPI _schoolLocalRepository;
リポジトリは内部で持ってる方がいいと思うんだけど、どうして無くしたのか説明が欲しいかも。

2023-12-28 13:39 UTC, mic4dy commented on lib/view_model/single_page/signup/signup_view_model.dart
> -  late final SchoolsLocalRepositoryAPI _schoolLocalRepository;
内部で持ってる方がいい理由は依存先をAPIにできるのでテスタブルになること。

2023-12-28 13:39 UTC, mic4dy commented on lib/view/component/dialog/signing_up_dialog.dart
> +    final AsyncValue<SignupState> state = ref.watch(signupViewModelProvider);
二つ以上のstateを見るなら命名変更した方がわかりやすい。

2023-12-28 13:39 UTC, mic4dy commented on lib/view/component/form/error_indication.dart
このformディレクトリが全体のcompornentにあるのがなんか違和感感じるから、form -> signing_formにするかsignupのところにあるのが良い気がする。

2023-12-28 13:39 UTC, mic4dy commented on lib/view/user_settings/user_delete_dialog.dart
> +      body: const Text('お子様を削除しますか？'),
DELETEなのでもう少し丁寧な文章の方がいいかも。
以下を追加しよう。
「お子様情報の削除を実行した場合，取り消すことはできません．」

2023-12-28 13:39 UTC, mic4dy commented on lib/view_model/single_page/user_settings/user_settings_view_model.dart
> +  }
全然仕様を話してなかったんだけど、ユーザを削除したときにその学校のユーザが他にいなかった場合、学校の献立情報をSQLiteから削除するべきか検討した方がいいかも。
正直どっちでもいいからアトリが決めてNotionに残しておいてほしい。

2023-12-28 13:39 UTC, mic4dy commented on lib/view/user_settings/user_settings.dart
> +                ),
こういうのはSizeのConstantsを見に行って欲しいかも〜。

2023-12-28 13:39 UTC, mic4dy commented on lib/view/user_settings/user_settings.dart
> +          routemaster.push('/home/user_settings/-1');
-1がマジックナンバーになってるのが気になるかも。
Constantsとかに新規ユーザ用の変数って意味合いで作っておくのが良さそう。

2023-12-28 13:39 UTC, mic4dy commented on lib/view/user_settings/user_switch_dialog.dart
> +      body: const Text('選択中のお子様を変更しますか？'),
変更だと編集と意味合いが似ているので以下の表現の方が良いな。
```suggestion
      body: const Text('選択中のお子様を切り替えますか？'),
```

2023-12-31 01:09 UTC, Atori-Ikeyama commented on lib/view_model/multi_page/user/user_view_model.dart
> +
仕様を変えたのそもそも必要なくなっていたので消しました

2023-12-31 01:09 UTC, Atori-Ikeyama commented on lib/view_model/multi_page/user/user_view_model.dart
> +    await ref.read(userSettingsViewModelProvider.notifier).updateUsers();
仕様を変えたのそもそも必要なくなっていたので消しました

2023-12-31 01:27 UTC, Atori-Ikeyama commented on lib/view_model/single_page/signup/signup_view_model.dart
> +    }
build methodの中なので`updateName` `updateSchool` `updateSchoolYear`をうまく使う方法がわからなかったです．
`schoolYears`の値の処理だけ関数にまとめました．

2023-12-31 01:41 UTC, Atori-Ikeyama commented on lib/view_model/single_page/signup/signup_view_model.dart
> -  late final SchoolsLocalRepositoryAPI _schoolLocalRepository;
テストに関しては、efで参照する方法でもできるようです．（[参考](https://riverpod.dev/ja/docs/cookbooks/testing#%E3%83%97%E3%83%AD%E3%83%90%E3%82%A4%E3%83%80%E3%81%AE%E6%8C%99%E5%8B%95%E3%82%92%E3%82%AA%E3%83%BC%E3%83%90%E3%83%BC%E3%83%A9%E3%82%A4%E3%83%89%E3%81%99%E3%82%8B)）
refで参照する方がシンプルでデファクトな書き方なのかなと思って無くしましたが、それ以上の理由はないです．

2023-12-31 01:51 UTC, Atori-Ikeyama commented on lib/view/component/form/error_indication.dart
このformたちは，`user_settings_detail.dart`と`signup.dart`の二箇所から呼ばれているので，signupには置かずにform -> signing_formにしました

2023-12-31 09:15 UTC, Atori-Ikeyama commented on lib/view_model/single_page/user_settings/user_settings_view_model.dart
> +  }
ユーザの行動を考えた際，削除しなかったファイルの容量が問題になることはないと思われるので，
とりあえず削除しないことにします．
今後削除する方針にする方が良い気もしますが，今後のタスクとしてイシューに上げておきます（#178）

2024-01-04 08:46 UTC, mic4dy commented on lib/view_model/single_page/signup/signup_view_model.dart
> -  late final SchoolsLocalRepositoryAPI _schoolLocalRepository;
なるへそ、このままで良さそうやな。

2024-01-04 08:50 UTC, mic4dy approved these changes
![LGTM](https://image.lgtmoon.dev/232814)

2024-01-04 23:17 UTC, merged