Riverpod 2.x への移行
Hakondate/Hakondate pull request #118
Opened 2023-06-17 14:03 UTC by mic4dy

**Issueリンク**

#106 #107

**実装したこと**

- [ ] 各種Providerをコードジェネレータを使ったコードへ置き換え

**実装しなかったこと**

- 特になし

**スクリーンショット**

**補足事項**

- 特になし

**セルフレビュー**

- [ ] コーディング規約に沿ったコードを書いた
    - ファイル末尾の改行
    - Widgetの階層構造
    - 静的型付け
    くらいは少なくとも確認する
- [ ] 提出予定のファイルを確認し不要な変更やファイルが混入していないかを確認した

2023-06-29 14:43 UTC, Atori-Ikeyama requested changes

2023-06-29 14:43 UTC, Atori-Ikeyama commented on lib/repository/local/sqlite/local_database.dart
マイグレーションにバグがありそうです．
起動すると通信エラーが発生しました．

2023-07-01 14:29 UTC, mic4dy commented on lib/repository/local/sqlite/local_database.dart
今回はバージョンアップ必要なかったっぽい
次以降のバージョンアップにも対応できるように関数だけ用意した

2023-07-01 14:31 UTC, mic4dy commented
@Atori-Ikeyama 
全部修正できたから確認よろみ〜

2023-07-06 11:16 UTC, Atori-Ikeyama approved these changes
LGTM
![LGTM](https://github.com/Hakondate/Hakondate/assets/49859718/a9f27145-02e0-4dcd-addf-b8be9451a014)

2023-07-06 11:17 UTC, merged