ユーザ情報のマイグレーション
Hakondate/Hakondate pull request #123
Opened 2023-07-03 14:13 UTC by mic4dy

**Issueリンク**

#121 

**実装したこと**

- [x] v1のユーザ情報の読み取り
- [x] v2への変換・保存
- [x] migrationの実行判断
- [x] debugPrintのライブラリ統一
- [ ] 実際に確認する

**実装しなかったこと**

- 特になし

**スクリーンショット**

**補足事項**

- 特になし

**チェックリスト**

- [x] 提出予定のファイルを確認し不要な変更やファイルが混入していないかを確認した
- [x] 環境変数や秘匿情報を扱うファイルの変更を適切に行なった（または変更していない）
    - [ ] 管理情報の更新を行なった
    - [ ] 該当ファイルを保存場所にアップロードした

2023-07-03 14:14 UTC, mic4dy commented
雰囲気で一通り実装したけど、確認の術がない・・・
実際にv1と同じ書き込みのコードも用意してデバッグしてみる（パッケージのバージョンアップで書き込み方変わってたら知らん）

2023-07-04 11:53 UTC, mic4dy commented
デモ用のコミットを作った
68935a2

2023-07-04 11:55 UTC, mic4dy commented
全部実装＆確認完了〜
レビューよろみです！

2023-07-13 11:03 UTC, Atori-Ikeyama requested changes

2023-07-20 12:55 UTC, Atori-Ikeyama commented
### 確認したこと
- [ ] 新規で起動する
- [ ] version1のユーザー情報がある
  - [ ] child.jsonが削除される
  - [ ] child.jsonの情報でユーザーが作成されている
  - [ ] 2回目以降の起動が問題なくできる

2023-07-20 12:56 UTC, Atori-Ikeyama approved these changes
![LGTM](https://github.com/Hakondate/Hakondate/assets/49859718/87522814-097b-4cd7-9cb1-bef5de796b97)

2023-07-20 12:57 UTC, merged