ヘルプ機能の実装
Hakondate/Hakondate pull request #128
Opened 2023-07-15 08:23 UTC by tauto1127

**Issueリンク**

#

**実装したこと**

- [ ] 

**実装しなかったこと**

- 特になし

**スクリーンショット**

**補足事項**

- 特になし

**チェックリスト**

- [ ] 提出予定のファイルを確認し不要な変更やファイルが混入していないかを確認した
- [ ] 環境変数や秘匿情報を扱うファイルの変更を適切に行なった（または変更していない）
    - [ ] 管理情報の更新を行なった
    - [ ] 該当ファイルを保存場所にアップロードした

2023-07-15 09:21 UTC, mic4dy commented
新しく機能を作るときの考え方（一例）
1. 機能の仕様を考える
2. Modelが新規に必要か（新しい概念の定義が必要か）
3. Repositoryを利用するか（外部との連携が必要か）
4. Stateが必要か（画面に対して変数の定義が必要か）
5. ViewModelが必要か（画面にどんな処理が必要か）→今回は必要
     ※ 画面の遷移の処理は基本省略可能
6. Viewが必要か→今回は必要
7. 上から必要なものを作っていく

2023-07-15 10:39 UTC, mic4dy commented
栄養基準値のリンク
https://www.mext.go.jp/content/20210212-mxt_kenshoku-100003357_2.pdf

2023-07-15 10:55 UTC, mic4dy commented
カロリー変換
https://judge.u-aizu.ac.jp/onlinejudge/description.jsp?id=0239#:~:text=%E9%A3%9F%E3%81%B9%E7%89%A9%E3%81%AB%E3%81%AF3%E5%A4%A7,kcal%20%E3%81%A8%E8%A8%88%E7%AE%97%E3%81%95%E3%82%8C%E3%81%BE%E3%81%99%E3%80%82

2023-07-15 11:10 UTC, mic4dy commented
％表示されている基準値（グラム）の求め方
1. エネルギーに倍率をかける（炭水化物は50~65%なので57.5％をかける）
2. 各栄養素のkcla:gに基づいて変換
    - 脂質9:1
    - 炭水化物4:1
    - タンパク質4:1

2023-08-15 14:38 UTC, tauto1127 commented
炭水化物
https://www.mhlw.go.jp/content/10904750/000586559.pdf

2023-08-16 13:24 UTC, tauto1127 commented
![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-16 at 22 22 00](https://github.com/Hakondate/Hakondate/assets/44548782/044d1e2c-5eb4-4562-97e6-c88743cb4021)
![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-16 at 22 21 57](https://github.com/Hakondate/Hakondate/assets/44548782/5a4185f0-5b4d-478f-8999-f9eb256ba473)
![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-16 at 22 21 52](https://github.com/Hakondate/Hakondate/assets/44548782/c5b1a7e9-1049-420f-ba35-2877306927d3)
![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-16 at 22 22 04](https://github.com/Hakondate/Hakondate/assets/44548782/2f2456b0-13bd-402e-908b-84549900b053)

2023-08-21 04:01 UTC, mic4dy reviewed
軽くみた

2023-08-21 04:01 UTC, mic4dy commented on lib/state/user/school_grade.dart
> +  junior(slnsJsonFileName: 'junior.json', slnsImageFileName: 'junior.png');*/
不要なコメント削除

2023-08-21 04:04 UTC, mic4dy commented
linterが通っていない場合は要修正と、これ栄養基準値のデータあまり変わってなさそうだけど、ちゃんと計算した？（計算式自体変えた気がするから値も結構変わると思う）

2023-08-21 04:05 UTC, mic4dy commented
もうちょい後でちゃんとみます！

2023-08-21 11:12 UTC, mic4dy requested changes

2023-08-21 11:12 UTC, mic4dy commented on lib/state/user/school_grade.dart
> +  junior(slnsJsonFileName: 'junior.json', slnsImageFileName: 'juniorSLIS.png', slnsZincFileName: 'juniorZinc.png');
ファイル名は定数名に揃える
`lowerSLIS`など

2023-08-21 11:12 UTC, mic4dy commented on lib/state/user/school_grade.dart
> +  final String slnsJsonFileName;
空行

2023-08-21 11:12 UTC, mic4dy commented on lib/state/user/school_grade.dart
> +  final String slnsJsonFileName;
```suggestion
  });
  
  final String slnsJsonFileName;
```

2023-08-21 11:12 UTC, mic4dy commented on lib/view/help/help.dart
> +  }
プッシュ済みなのでInformationから引っ張ってきて良き

2023-08-21 11:12 UTC, mic4dy commented on lib/view/help/help_frame.dart
> +            //final HelpState state = ref.watch(helpViewModelProvider as ProviderListenable<HelpState>);//キャスト
削除

2023-08-21 11:12 UTC, mic4dy commented on lib/view/help/help.dart
> +import '../component/frame/fade_up_app_bar.dart';
フルパスで書こう

2023-08-21 11:12 UTC, mic4dy commented on lib/view/help/help_frame.dart
文面確定してから再レビューする

2023-08-21 11:12 UTC, mic4dy commented on lib/view_model/single_page/help/help_view_model.dart
> +    return HelpState(
```suggestion
    final SchoolGrade schoolGrade = await ref.read(userViewModelProvider.notifier).getSchoolGrade(user.id);
    
    return HelpState(
```

2023-08-21 11:36 UTC, mic4dy commented
- [学校給食実施基準](https://www.mext.go.jp/a_menu/sports/syokuiku/1407704.htm) : https://www.mext.go.jp/a_menu/sports/syokuiku/1407704.htm
- [日本人の食事摂取基準](https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/kenkou/eiyou/syokuji_kijyun.html) : https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/kenkou/eiyou/syokuji_kijyun.html

2023-08-23 01:15 UTC, mic4dy requested changes
とりあえず全部一旦見直しました〜〜〜

2023-08-23 01:15 UTC, mic4dy commented on lib/state/user/school_grade.dart
> +  junior(slnsJsonFileName: 'junior.json', slnsImageFileName: 'juniorSLIS.png', slnsZincFileName: 'juniorZinc.png');
ここは改行しながらの方が見やすいかも。
```suggestion
  lower(
    slnsJsonFileName: 'lower.json',
    slnsImageFileName: 'lowerSLIS.png',
    slnsZincFileName: 'elementalZinc.png',
  ),
  middle(
    slnsJsonFileName: 'middle.json',
    slnsImageFileName: 'middleSLIS.png',
    slnsZincFileName: 'elementalZinc.png',
  ),
  upper(
    slnsJsonFileName: 'upper.json',
    slnsImageFileName: 'upperSLIS.png',
    slnsZincFileName: 'elementalZinc.png',
  ),
  junior(
    slnsJsonFileName: 'junior.json',
    slnsImageFileName: 'juniorSLIS.png',
    slnsZincFileName: 'juniorZinc.png',
  );
```

2023-08-23 01:15 UTC, mic4dy commented on lib/view/help/help.dart
> +  }
`feature/information`から引っ張ってきておk（修正済み）

2023-08-23 01:15 UTC, mic4dy commented on lib/view/help/help.dart
> +class Help extends StatelessWidget{
```suggestion
class Help extends StatelessWidget {
```

2023-08-23 01:15 UTC, mic4dy commented on lib/view/help/help_frame.dart
> +  });
これを一番上に書く

2023-08-23 01:15 UTC, mic4dy commented on lib/view/help/help_frame.dart
文言Notion確認して大丈夫そうなら更新しておk

2023-08-27 00:55 UTC, tauto1127 commented
レビューありがとうございます
指摘されたところ、全て修正しました
栄養基準値の表はHTMLで作ったらいい感じになりました
またレビューよろしくお願いします

2023-08-30 07:47 UTC, mic4dy requested changes
テスト転けてるのでそこから修正よろみ。
コンフリクトが大量に発生してそうなのでそこの解消にあたる。
もしかしたらInformationブランチの影響かもしれないから、そっちを最新の取り込むところから始めてみるのが良さそう。

2023-08-30 07:47 UTC, mic4dy commented on assets/slns/image/graphFormula.png
できれば右辺は中央揃えより左詰めの方がいいかも。

2023-08-30 07:47 UTC, mic4dy commented on assets/slns/image/graphFormula.png
あとSLISの方では外枠が綺麗に囲われているのに、こっちは角が内側からえぐられているのが気になる（この画像だけじゃないけど）。

2023-08-30 07:47 UTC, mic4dy commented on assets/slns/image/juniorSLIS.png
めちゃくちゃ良い。
けど、強いていうのであれば「エネルギー」の凡例の枠を少し細くしてほしい（めちゃ濃く見える）。
あと、各文字の色をアプリ内のBodyテキストのカラーコード（0xFF373737）と合わせていないのであれば合わせて欲しい（なんとなく濃く見える気がするけど合わせてるなら問題なし）。

2023-08-30 07:47 UTC, mic4dy commented on lib/view/help/help.dart
> +              ),
１要素なら一行で書いたほうが見やすい。
```suggestion
              const SizedBox(height: 20),
```

2023-08-30 07:47 UTC, mic4dy commented on lib/view/help/help.dart
> +              ),
あと`20`はマジックナンバーなのでMarginSizeとかに定義して使おう。

2023-08-30 07:47 UTC, mic4dy commented on lib/view/help/help.dart
> +              ),
同様

2023-08-30 07:47 UTC, mic4dy commented on lib/view/help/help.dart
> +      ),
一行で大丈夫
```suggestion
      appBar: const FadeUpAppBar(title: Text('ヘルプ')),
```

2023-08-30 07:47 UTC, mic4dy commented on lib/view/help/help_frame.dart
> +        label: '基準値について',
インデントが二つ分入ってる。
全体的に上げる。
```suggestion
  factory HelpFrame.baseNut() => HelpFrame(
    label: '基準値について',
```

2023-08-30 07:47 UTC, mic4dy commented on lib/view/help/help_frame.dart
> +                return state.when(
```suggestion
                final AsyncValue<HelpState> state = ref.watch(helpViewModelProvider);
                
                return state.when(
```

2023-08-30 07:47 UTC, mic4dy commented on lib/view/help/help_frame.dart
> +        label: '基準値について',
何ヶ所か崩れているので全体的に見直す。

2023-08-30 07:47 UTC, mic4dy commented on lib/view/help/help_frame.dart
> +                              DescriptionText.linked(label: '日本人の食事摂取基準（2020年）', url: 'https://www.mhlw.go.jp/stf/newpage_08517.html', isAnnotation: true)
要素が複数ならは改行する。
改行した時はインデントは1個だけ下げる。
全体的に間違っている箇所があるので修正。

2023-08-30 07:47 UTC, mic4dy commented on lib/view/help/help_frame.dart
> +  static Widget _iconWithText(String text, IconData icon) {
引数が文字列なら`label`にしたいかな。
`text`はWidgetとも取れる。

2023-09-03 23:42 UTC, tauto1127 commented on assets/slns/image/juniorSLIS.png
https://[tauto1127.github.io/hakondateTable/](https://tauto1127.github.io/hakondateTable/)
修正してみました　どうですか？？

2023-09-05 09:59 UTC, mic4dy requested changes
ここだけ直せばマージできそうや〜

2023-09-05 09:59 UTC, mic4dy commented on lib/view/help/help.dart
> +        padding: const EdgeInsets.only(left: MarginSize.normalVertical, right: MarginSize.normalVertical),
左右同じ値なら`only`じゃなくて`symmetric`を使おう
あとサイズは`PaddingSize.normal`くらいが良さそう

2023-09-05 09:59 UTC, mic4dy commented on lib/view/help/help.dart
> +
これは親の`Padding`に統合しましょ〜
それでUI崩れるならば`SingleChildScrollView`を一番上層に持ってくれば多分解決できる

2023-09-05 09:59 UTC, mic4dy commented on lib/view/help/help.dart
> +              const SizedBox(height: MarginSize.normalHorizontal),
これも同じく

2023-09-05 11:40 UTC, tauto1127 commented
直しました！

2023-09-08 01:28 UTC, mic4dy approved these changes
![LGTM](https://images.lgtmgen.org/93e81fb4-d473-4598-8734-4595f4d0c95b)

2023-09-08 01:28 UTC, mic4dy commented on lib/constant/size.dart
>    static const double subheading = 20;  // 副見出し
ここInfoの方で変更するからやっぱ大丈夫！

2023-09-08 04:39 UTC, mic4dy requested changes
ごめん！やっぱ一個修正してほしい！

2023-09-08 04:39 UTC, mic4dy commented on lib/view/help/help.dart
> +        padding: const EdgeInsets.symmetric(vertical: MarginSize.normal, horizontal: MarginSize.normalHorizontal),
ここやっぱり前述したようにPaddingの取り方が変になってるから階層をいじって正しくしてほしい。
具体的にはスクロールの途中のものは上下にPaddingを入れないように変更する。
SingleChildScrollView > Padding > Column の順にすれば治ると思う。

![image](https://github.com/Hakondate/Hakondate/assets/96598562/e7b39fe7-953f-40e5-9d62-fcfe88dc65cc)

2023-09-08 04:40 UTC, mic4dy commented on lib/view/help/help.dart
> +        padding: const EdgeInsets.symmetric(vertical: MarginSize.normal, horizontal: MarginSize.normalHorizontal),
あと要素二つなので改行もよろみ

2023-09-11 11:15 UTC, mic4dy approved these changes
![LGTM](https://images.lgtmgen.org/796fc6f3-0642-485b-aada-872f837072eb)

2023-09-11 12:51 UTC, merged