[add] implement multi-user update menus
Hakondate/Hakondate pull request #135
Opened 2023-08-15 06:45 UTC by Atori-Ikeyama

**Issueリンク**

#

**実装したこと**

- [ ] 

**実装しなかったこと**

- 特になし

**スクリーンショット**

**補足事項**

- 特になし

**チェックリスト**

- [ ] 提出予定のファイルを確認し不要な変更やファイルが混入していないかを確認した
- [ ] 環境変数や秘匿情報を扱うファイルの変更を適切に行なった（または変更していない）
    - [ ] 管理情報の更新を行なった
    - [ ] 該当ファイルを保存場所にアップロードした

2023-08-15 07:40 UTC, Atori-Ikeyama commented
### 検証方法

1. シミュレータ上のアプリを一度消し，テスト中学校でログインする
2. daily画面の右下にあるフローティングアクションボタンを押す（test2という名前で巴中の2年のユーザーが追加される）
3. デバッグコンソールに，ダウンロードすべきデータが全てあるか確認する

2023-08-15 08:16 UTC, mic4dy commented on lib/view_model/multi_page/user/user_view_model.dart
> +  }
流し見してて気になったのでコメント。

命名と実装場所が微妙（デバッグ用なら問題なし）。
UserViewModelはアプリ起動時のユーザ、つまりCurrentUserを扱うViewModelなので複数ユーザにまたがるRepositoryライクな利用方法は責務が脅かされる。
適切な実装位置は`UserSettingsViewModel`になる。

2023-09-11 14:04 UTC, mic4dy requested changes

2023-09-11 14:04 UTC, mic4dy commented on lib/view_model/single_page/user_settings/user_settings_view_model.dart
> +  Future<List<int>> getParentIdList() async {
Splashで実装するのが良き

2023-09-12 18:40 UTC, Atori-Ikeyama commented
- getParentIdList()はsplashに移動
- getParentIdList()のロジックをもっとシンプルに
  - DriftのSQLのwhere inに相当するもので実装

2023-09-18 11:24 UTC, Atori-Ikeyama commented on lib/view_model/single_page/user_settings/user_settings_view_model.dart
> +  Future<List<int>> getParentIdList() async {
この関数，前話した時にはsplashで使っているって言っちゃったんですが，splashのinitilizeMenus()で呼ぶ，menusRemoteRepository.get()の中で使われていました．
それでもsplashで実装するので良いですか？
おそらくこの関数はsplash駆動の時しか使用されないと思うのですが，splashで呼ばれた別のview modelがsplashの中の関数を呼ぶことになるので，少し違和感がある気もします...

2023-09-24 06:32 UTC, mic4dy commented
↑テストこけてるんでそこ修正後に見るね〜

2023-10-02 08:10 UTC, Atori-Ikeyama commented
修正しましたー

2023-10-02 10:08 UTC, mic4dy requested changes
とりま見た

2023-10-02 10:08 UTC, mic4dy commented on lib/repository/local/sqlite/schools/schools_local_repository.dart
> +    final List<int> parentIds = schoolsSchemas.map((SchoolsSchema schoolsSchema) => schoolsSchema.parentId).toSet().toList();
`selectOnly`でやりたいこと表現できそうな気がする。
https://zenn.dev/umatoma/articles/f9cfe3371a32f4

2023-10-02 10:08 UTC, mic4dy commented on lib/view_model/single_page/user_settings/user_settings_view_model.dart
> +      data: (UserSettingsState state) async => state.users!,
data→orElseの順の方が読みやすいかな。
asyncなくてもアロー関数だから非同期で動きそうな気がするけどどうなんやろ。

2023-10-16 10:23 UTC, mic4dy commented on lib/repository/local/sqlite/schools/schools_local_repository.dart
> +    final List<int> parentIds = schoolsSchemas.map((SchoolsSchema schoolsSchema) => schoolsSchema.parentId).toSet().toList();
https://drift.simonbinder.eu/docs/dart-api/select/#group-by

2023-10-30 10:14 UTC, mic4dy approved these changes
![LGTM](https://images.lgtmgen.org/a44fde98-d643-4f35-923f-dc16be747569)

2023-10-30 10:15 UTC, merged