Feature/dictionary additional
Hakondate/Hakondate pull request #150
Opened 2023-11-13 09:06 UTC by tauto1127

**Issueリンク**

#

**実装したこと**

- [ ] 

**実装しなかったこと**

- 特になし

**スクリーンショット**

**補足事項**

- 特になし

**チェックリスト**

- [ ] 提出予定のファイルを確認し不要な変更やファイルが混入していないかを確認した
- [ ] 環境変数や秘匿情報を扱うファイルの変更を適切に行なった（または変更していない）
    - [ ] 管理情報の更新を行なった
    - [ ] 該当ファイルを保存場所にアップロードした

2023-11-28 07:03 UTC, mic4dy requested changes
おおかた良さそう〜ありがとう。
ロジック部分は見るのに時間かかるので、それ以外の部分だけ見ました。
ロジック関連は後でゆっくり見ます！

2023-11-28 07:03 UTC, mic4dy commented on lib/view/dictionary/dictionary_search.dart
> +                  Icons.delete_outline,
ゴミ箱じゃなくて「×」の方がいいかもしれない。

2023-11-28 07:03 UTC, mic4dy commented on lib/view_model/single_page/daily/daily_view_model.dart
> +  late final MenusLocalRepository _menusLocalRepository;
```suggestion
  late final MenusLocalRepositoryAPI _menusLocalRepository;
```

2023-11-28 07:03 UTC, mic4dy commented on lib/view_model/single_page/splash/splash_view_model.dart
この差分はいらないかな。

2023-11-30 01:54 UTC, tauto1127 commented on lib/view/daily/nutrients_card.dart
> +  }
https://github.com/Hakondate/Hakondate/commit/265d9dc74328a5a2f4b64af90810b93303b56863
こんな感じでEnumを作ってみたのですが，どうでしょうか？

また他の既存部分のリファクタリングというのはおすすめ食材の部分ですか？それともhakondate全体ですか？
hakondate全体で探してみても使えそうなとこはない気がします．

2023-11-30 02:09 UTC, tauto1127 commented on lib/view/daily/nutrients_card.dart
> +  }
あと"たんぱく質"と"タンパク質"がバラバラに使用されているのに気づきました．
dailyのグラフではたんぱく質
食材の栄養素一覧ではタンパク質

統一した方がいい気がします．他の栄養素はカタカナなのでカタカナがいいと思います

2023-12-06 07:45 UTC, mic4dy commented on lib/view/daily/nutrients_card.dart
> +  }
半分くらいは意図通りなんだけど、`energy`とかの文字列でアクセスすることに脆弱性があるので、それを排除するのもこの定数に任せるような処理にしてほしい。
具体的には`energy`ではなくて`MajorNutrient.energy`でアクセスする。

2023-12-06 10:49 UTC, mic4dy requested changes
まず、新規でIssueを立ててほしいと付けているものは修正前に立ててほしい。
立てないまま、忘れ去られるのが怖すぎるので。
あと、検索はLogとりたいのでそれもIsuue立てておいて！

2023-12-06 10:49 UTC, mic4dy commented on lib/repository/local/sqlite/dictionary_items/dictionary_items_local_repository.dart
> +}
- Utilに追加する
- 名前も命名規則っぽいのあったほうがいいからHogeExtensionで統一しよう
```suggestion
extension StringExtension on String {
  String toHiragana() {
    return replaceAllMapped(RegExp('[ァ-ヴ]'), (Match match) => String.fromCharCode(match.group(0)!.codeUnitAt(0) - 0x60));
  }
  
  String toKatakana() {
    return replaceAllMapped(RegExp('[ぁ-ゔ]'), (Match match) => String.fromCharCode(match.group(0)!.codeUnitAt(0) + 0x60));
  }
}
```

2023-12-06 10:49 UTC, mic4dy commented on lib/repository/local/sqlite/dictionary_items/dictionary_items_local_repository.dart
> +  Future<List<DictionaryItemModel>> search(String query) async{
継承元と同じ順番で実装したほうがわかりやすいかな。

2023-12-06 10:49 UTC, mic4dy commented on lib/repository/local/sqlite/dictionary_items/dictionary_items_local_repository.dart
> +      .get()..sort((DictionaryItemsSchema a,DictionaryItemsSchema b) => a.name.compareTo(b.name));
流石にこれだけ長くなってしまうなら、条件は改行しながら列挙したほうがいいかな。
あと他のクラスに統一して`tbl`を`t`にしてほしい。

2023-12-06 10:49 UTC, mic4dy commented on lib/repository/local/sqlite/dictionary_items/dictionary_items_local_repository.dart
> +      .get()..sort((DictionaryItemsSchema a,DictionaryItemsSchema b) => a.name.compareTo(b.name));
```suggestion
      .get()..sort((DictionaryItemsSchema a, DictionaryItemsSchema b) => a.name.compareTo(b.name));
```

2023-12-06 10:49 UTC, mic4dy commented on lib/state/daily/daily_state.dart
> +    @Default(<MajorNutrient, List<DictionaryItemModel>> {}) Map<MajorNutrient, List<DictionaryItemModel>> recommendDishes,
命名が不適切

2023-12-06 10:49 UTC, mic4dy commented on lib/state/dictionary/dictionary_state.dart
> +    @Default(<DictionaryItemModel> [])List<DictionaryItemModel> searchedItems,
```suggestion
    @Default(<DictionaryItemModel>[]) List<DictionaryItemModel> searchedItems,
```

2023-12-06 10:49 UTC, mic4dy commented on lib/view/daily/nutrients_card.dart
ファイルが肥大化しているので別ファイルに書き分ける感じの方がいい

2023-12-06 10:49 UTC, mic4dy commented on lib/view/daily/nutrients_card.dart
> +                      _recommendFoodWidget(data.recommendDishes,1),
Index渡しはマジックナンバーになってしまうので避ける。

2023-12-06 10:49 UTC, mic4dy commented on lib/view/daily/nutrients_card.dart
> +                }else{
基本的なコーディング規約が守れていない部分が他にも多いのでEffectiveDartを読んで整形しよう（気付いたところは指摘するけど）。
```suggestion
                } else {
```

2023-12-06 10:49 UTC, mic4dy commented on lib/view_model/single_page/daily/daily_view_model.dart
> +      },
不要な修正

2023-12-06 10:49 UTC, mic4dy commented on lib/view_model/single_page/daily/daily_view_model.dart
> +    (
不要な修正

2023-12-06 10:49 UTC, mic4dy commented on lib/view/daily/nutrients_card.dart
> +      builder: (BuildContext context, WidgetRef ref, Widget? widet) {
使わない変数は`_`にする。
```suggestion
      builder: (BuildContext context, WidgetRef ref, _) {
```

2023-12-06 10:49 UTC, mic4dy commented on lib/view/daily/nutrients_card.dart
> +                  ref.read(dictionaryViewModelProvider.notifier).selectItem(list[index].id);
非同期関数は`async/await`を使って呼び出そう

2023-12-06 10:49 UTC, mic4dy commented on lib/view/dictionary/dictionary.dart
> +              ref.read(dictionaryViewModelProvider.notifier).initializeSearchedList();
async/awaitで呼び出す

2023-12-06 10:49 UTC, mic4dy commented on lib/view_model/single_page/daily/daily_view_model.dart
> +      await ref.read(dailyViewModelProvider.notifier).updateRecommendDishes();
自分自身をProvider経由で呼ばない

2023-12-06 10:49 UTC, mic4dy commented on lib/model/nutrients/nutrient_major.dart
> +enum MajorNutrient {
「五大栄養素」という固有名詞の英語が適切なので論文とかでどう訳されているのかを参照してそれにしよう
そもそも、五大栄養素のみを扱うのも少し違う気がするけど…（この後の修正によっては全栄養素が入る可能性ある）

2023-12-06 10:49 UTC, mic4dy commented on lib/view_model/single_page/dictionary/dictionary_view_model.dart
> +        searchedItems: await _dictionaryItemsLocalRepository.search(expression),
引数名とかは統一する

2023-12-06 10:49 UTC, mic4dy commented on lib/view_model/single_page/dictionary/dictionary_view_model.dart
> +        ),
```suggestion
      ),
```

2023-12-27 12:30 UTC, mic4dy requested changes
あと少し！

2023-12-27 12:30 UTC, mic4dy commented on lib/view/dictionary/recommend_incredients.dart
> +  Widget _rankingContents(List<DictionaryItemModel> list, FiveMajorNutrient key) {
変数名がわかりにくいので意味のある単語に変更する

2023-12-27 12:30 UTC, mic4dy commented on lib/view/dictionary/recommend_incredients.dart
> +          recommendIncredients.entries.elementAt(index).key,
分けて渡す必要なさそう

2023-12-27 12:30 UTC, mic4dy commented on lib/model/nutrients/nutrient_five_major.dart
> +  double getNutrient(DictionaryItemModel item){
文字列を用いた判定を行わないために定数化しているのでこのような関数は使わない実装をする
この場合は、DictionaryItemModel（かそれを扱うViewModel）にFiveMajorNutrientを受け取って各値を返す関数を実装する

2023-12-27 12:30 UTC, mic4dy commented on lib/view/dictionary/dictionary_search.dart
> +  final TextEditingController _controller = TextEditingController();
Viewでプロパティは使わない
これを消すとconstにできるのでrouteも合わせて変更する

2023-12-27 12:30 UTC, mic4dy commented on lib/util/extension/string_extension.dart
> +  String toKatakana() {
```suggestion
  }
  
  String toKatakana() {
```

2023-12-27 12:30 UTC, mic4dy commented on lib/view/daily/nutrients_card.dart
> +          const RecommendedIncredientExpansionTile(),
このサービスではIncredientではなくてFoodStuffで統一する

2023-12-27 12:30 UTC, mic4dy commented on lib/view/dictionary/dictionary_search.dart
> +  final TextEditingController _controller = TextEditingController();
Stateに持たせるのが良さそうかな

2023-12-27 12:30 UTC, mic4dy commented on lib/view/dictionary/dictionary_search.dart
> +                  ref.read(dictionaryViewModelProvider.notifier).clearQuery();
非同期処理に書き換える

2023-12-27 12:30 UTC, mic4dy commented on lib/view/dictionary/dictionary_search.dart
> +              ),
```suggestion
              separatorBuilder: (_, __) => const Divider(
                height: 0,
              ),
```

2024-01-04 01:58 UTC, tauto1127 commented
GASの方もレビューをよろしくお願いします🙇

2024-01-05 11:02 UTC, mic4dy requested changes

2024-01-05 11:02 UTC, mic4dy commented on lib/view_model/single_page/dictionary/dictionary_search_view_model.dart
> +  }
```suggestion
  Future<DictionarySearchState> build() async {
    _dictionaryItemsLocalRepository =
        ref.watch(dictionaryItemsLocalRepositoryProvider);
        ref.onDispose(() => state.whenData((DictionarySearchState data) => data.searchBarTextController.dispose()));
        
    return DictionarySearchState(
      searchBarTextController: TextEditingController(),
      searchedItems: await _dictionaryItemsLocalRepository.getAll(),
    );
  }
```

2024-01-05 12:31 UTC, mic4dy approved these changes
![LGTM](https://images.lgtmgen.org/0b9561d5-47b7-4703-ae5f-f74d19349917)

2024-01-05 12:35 UTC, merged