GitHub Actions の見直し
Hakondate/Hakondate pull request #165
Opened 2023-11-22 12:45 UTC by mic4dy

2023-11-22 15:26 UTC, mic4dy commented
やっぱBotにPushさせた後に再評価するのは難しそうだし意味も薄そうに感じたので、綺麗にすることにとどめた。
若干チャックも早くなったと思うし、この後のFormatterあたりも組み込みやすいと思うので一旦これで見てみて。

2023-11-29 10:52 UTC, Atori-Ikeyama requested changes

2023-11-29 10:52 UTC, Atori-Ikeyama commented on .github/workflows/check_lint.yml
> +    if: github.event.pull_request.draft == false
```suggestion
    if: !github.event.pull_request.draft
```

2023-11-29 10:52 UTC, Atori-Ikeyama commented on .github/workflows/run_generator_and_sorter.yml
> +    if: github.event.pull_request.draft == false
```suggestion
    if: !github.event.pull_request.draft
```

2023-11-29 11:03 UTC, Atori-Ikeyama approved these changes
![giphy](https://github.com/Hakondate/Hakondate/assets/49859718/cd81dfd3-2ac6-4743-95a4-45c87407358b)

2023-11-29 11:03 UTC, merged