図鑑検索ソート順改善
Hakondate/Hakondate pull request #188
Opened 2024-02-05 13:37 UTC by tauto1127

**Issueリンク**

#

**実装したこと**

- [ ] 

**実装しなかったこと**

- 特になし

**スクリーンショット**

**補足事項**

- 特になし

**チェックリスト**

- [ ] 提出予定のファイルを確認し不要な変更やファイルが混入していないかを確認した
- [ ] 環境変数や秘匿情報を扱うファイルの変更を適切に行なった（または変更していない）
    - [ ] 管理情報の更新を行なった
    - [ ] 該当ファイルを保存場所にアップロードした

2024-03-27 11:53 UTC, Atori-Ikeyama reviewed
ほとんどOKです．
少し冗長な書き方があったのでそこだけ修正お願いします

2024-03-27 11:53 UTC, Atori-Ikeyama commented on lib/repository/local/sqlite/dictionary_items/dictionary_items_local_repository.dart
> +    return left || right;
```suggestion
    return name.contains(RegExp('(^|$wordSplitter)$query($wordSplitter|\$)'));
```

2024-03-27 11:53 UTC, Atori-Ikeyama commented on lib/repository/local/sqlite/dictionary_items/dictionary_items_local_repository.dart
> +    return left || right;
[^$wordSplitter]やと無理でしたー．[]の中で^を使うと否定の意味になるらしいです．（[参考](https://userweb.mnet.ne.jp/nakama/#:~:text=%E3%81%93%E3%81%AE%E3%82%88%E3%81%86%E3%81%AB%5B%20%5D%E3%81%AE%E4%B8%AD%E3%81%A7%20%5E%20%E3%81%8C%E4%BD%BF%E7%94%A8%E3%81%95%E3%82%8C%E3%81%9F%E5%A0%B4%E5%90%88%E3%81%AF%E3%80%81%E8%A1%8C%E3%81%AE%E5%85%88%E9%A0%AD%E3%82%92%E8%A1%A8%E3%81%99%20%5E%20%E3%81%A8%E3%81%AF%E6%84%8F%E5%91%B3%E3%81%8C%E7%95%B0%E3%81%AA%E3%82%8A%E3%81%BE%E3%81%99)）

2024-04-08 06:15 UTC, Atori-Ikeyama approved these changes
![cd6dc344-968c-599c-ed7c-8620576ded02](https://github.com/Hakondate/Hakondate/assets/49859718/c00674e9-d54b-4139-8e77-3d016f23f04a)

2024-04-08 11:31 UTC, mic4dy requested changes

2024-04-08 11:31 UTC, mic4dy commented on lib/repository/local/sqlite/dictionary_items/dictionary_items_local_repository.dart
>            ))
```dart
t.name.contains(query) | t.name.contains(query.toHiragana()) | t.name.contains(query.toKatakana()),
```
↓
```dart
t.name.toHiragana().contains(query.toHiragana()),
```

2024-04-08 11:31 UTC, mic4dy commented on lib/repository/local/sqlite/dictionary_items/dictionary_items_local_repository.dart
> +      _dictionarySearchItemNameCompare(left.name.toHiragana(), right.name.toHiragana(), query.toHiragana());
`_dictionarySearchItemNameCompare`の頭で同様の処理をすれば良い

2024-04-08 11:31 UTC, mic4dy commented on lib/repository/local/sqlite/dictionary_items/dictionary_items_local_repository.dart
> +  int _dictionarySearchItemNameCompare(String left, String right, String query) {
```suggestion
  int _compareSearchHit(String left, String right, String query) {
```

2024-04-08 11:31 UTC, mic4dy commented on lib/repository/local/sqlite/dictionary_items/dictionary_items_local_repository.dart
> +
Docコメント（仕様）を書く
- 完全内包している単語同士の比較であること
- 比較ロジックの説明（なんだと優先度が高いか）
- 返り値の示す値の意味（ `1`だとなんなのか）

2024-04-08 11:31 UTC, mic4dy commented on lib/repository/local/sqlite/dictionary_items/dictionary_items_local_repository.dart
> +    rightIndexOfQuery = right.indexOf(query);
```suggestion
    final int leftIndexOfQuery = left.indexOf(query);
    final int rightIndexOfQuery = right.indexOf(query);
```

2024-04-08 11:31 UTC, mic4dy commented on lib/repository/local/sqlite/dictionary_items/dictionary_items_local_repository.dart
> +    final bool isRightSpaceDelimitedWord = _isSpaceDelimited(right, rightIndexOfQuery, query);
- 全角を考慮する
- スペースでSplitしてIndexOfしたら正規表現使わなくても同様の一致探索ができそう（正規表現は重い）

2024-05-27 10:42 UTC, mic4dy approved these changes
![LGTM](https://firebasestorage.googleapis.com/v0/b/lgtmgen.appspot.com/o/images%2F19572ca7-ae87-4dc7-a77b-4635bd1089b5.jpg?alt=media&token=9a9e50a9-7088-452d-8ae8-79f9bc8748c2)

2024-05-27 10:43 UTC, merged