Redesign/recommend foodstuffs
Hakondate/Hakondate pull request #196
Opened 2024-03-27 11:51 UTC by AiriNakanishi

**Issueリンク**

#176

**実装したこと**

- [x] おすすめ食材のデザインの修正

**実装しなかったこと**

- 特になし

**スクリーンショット**
![Screenshot_1711540089](https://github.com/Hakondate/Hakondate/assets/143471957/a141e926-5cc9-48f0-93d3-6023a1fa7bac)

**補足事項**

- 特になし

**チェックリスト**

- [x] 提出予定のファイルを確認し不要な変更やファイルが混入していないかを確認した
- [x] 環境変数や秘匿情報を扱うファイルの変更を適切に行なった（または変更していない）
    - [ ] 管理情報の更新を行なった
    - [ ] 該当ファイルを保存場所にアップロードした

2024-04-02 10:56 UTC, tauto1127 requested changes

2024-04-02 10:56 UTC, tauto1127 commented on lib/view/dictionary/recommend_foodstuff.dart
> +                  '${recommendFoodStuffs.entries.elementAt(index).key.japaneseName}',
![Screenshot 2024-04-02 at 19 30 26](https://github.com/Hakondate/Hakondate/assets/44548782/b43d21f4-e29a-4e5a-b6bc-53ac48e24de7)
下のproblemを全部解消しよう

2024-04-02 10:56 UTC, tauto1127 commented on lib/view/dictionary/recommend_foodstuff.dart
> +        ),*/
イランコメ消す

2024-04-02 10:56 UTC, tauto1127 commented on lib/view/dictionary/recommend_foodstuff.dart
> +                    color: AppColor.ui.secondaryUltraLight,
comment

2024-04-02 10:56 UTC, tauto1127 commented on lib/view/dictionary/recommend_foodstuff.dart
> +                            padding: const EdgeInsets.symmetric(horizontal: 8),
マジックナンバーは使わない
基本的にlib/constant/のとこの定数を使う

2024-04-02 10:56 UTC, tauto1127 commented on lib/view/dictionary/recommend_foodstuff.dart
> +            //);
なんじゃこりゃ

2024-04-03 12:37 UTC, akari517 commented on devtools_options.yaml
このfileいらないかも

2024-04-09 14:07 UTC, uwatcha commented on devtools_options.yaml
確かに空ならいらないかもー

2024-05-19 07:53 UTC, Atori-Ikeyama commented
やっぱり開いた時のボーダーが気になる...
こんな感じで，`ExpantionTile`を`Theme`で囲って，`dividerColor`を透明にすると消せるから，消したいです．
```
return Theme(
          data: Theme.of(context).copyWith(dividerColor: Colors.transparent),
          child: ExpansionTile(
            title: const Text(
              'おすすめ食材',
              style: TextStyle(
                fontSize: FontSize.heading,
              ),
            ),
            onExpansionChanged: (bool value) => !value,
            textColor: AppColor.brand.secondary,
            iconColor: AppColor.brand.secondary,
            children: <Widget>[
              ref.watch(dailyViewModelProvider).maybeWhen(
                    data: (DailyState data) {
                      if (data.recommendFoodStuffs.isNotEmpty) {
                        return Column(
                          children: <Widget>[
                            for (int i = 0; i < data.recommendFoodStuffs.length; i++)
                              _recommendFoodWidget(
                                data.recommendFoodStuffs,
                                i,
                              ),
                          ],
                        );
                      } else {
                        return const SizedBox.shrink();
                      }
                    },
                    orElse: () => const SizedBox.shrink(),
                  ),
            ],
          ),
        );
```

2024-05-20 06:42 UTC, Atori-Ikeyama approved these changes
![cd6dc344-968c-599c-ed7c-8620576ded02](https://github.com/Hakondate/Hakondate/assets/49859718/a91a610a-b4a6-47a3-8eaa-9bc53eda2ae0)

2024-05-20 08:01 UTC, tauto1127 approved these changes

2024-05-20 08:03 UTC, uwatcha approved these changes

2024-05-20 08:04 UTC, merged