Fix/menus loading
Hakondate/Hakondate pull request #210
Opened 2024-06-17 08:55 UTC by uwatcha

**Issueリンク**

#191

**実装したこと**

- [x] 読み込む献立を、アプリ初期起動時から3ヶ月に限定し、献立の読み込み不良を解消した。（献立に更新があれば更新分を読み込む。）

**実装しなかったこと**
- [x] アプリ起動時に、はじめに選択している日の献立が読み込まれない問題がある。（）日付を切り替えて選択し直すと読み込まれる。

- 特になし

**スクリーンショット**

**補足事項**

- 特になし

**チェックリスト**

- [ ] 提出予定のファイルを確認し不要な変更やファイルが混入していないかを確認した
- [ ] 環境変数や秘匿情報を扱うファイルの変更を適切に行なった（または変更していない）
    - [ ] 管理情報の更新を行なった
    - [ ] 該当ファイルを保存場所にアップロードした

2024-06-17 09:33 UTC, tauto1127 commented
アプリ起動時に、はじめに選択している日の献立が読み込まれない問題がある。（）日付を切り替えて選択し直すと読み込まれる。
 実装しなかったのにチェック入ってるの気持ち悪くない？？？

2024-07-12 03:31 UTC, Atori-Ikeyama requested changes

2024-07-12 03:31 UTC, Atori-Ikeyama commented on lib/view_model/single_page/daily/daily_view_model.dart
> +    while (!state.hasValue) {
初回起動時に献立が表示されない問題を解決するなら，build関数を変えるべきだと思う．

2024-07-12 03:31 UTC, Atori-Ikeyama commented on lib/view_model/single_page/splash/splash_view_model.dart
> +    // ref.invalidate(dailyViewModelProvider);
消すならコメントアウトも消しちゃってOK

2024-07-12 03:32 UTC, Atori-Ikeyama commented
コンフリクトの解消と初回起動周りの問題だけ，俺が修正しちゃってもいい？

2024-07-17 15:55 UTC, mic4dy requested changes
こっちも見かけてたから見たとこだけ

2024-07-17 15:55 UTC, mic4dy commented on lib/view_model/single_page/daily/daily_view_model.dart
> +  Future<void> updateSelectedDay(DateTime selectedDay, {DateTime? focusedDay}) async {
引数の形変える必要ないかな

2024-07-17 16:03 UTC, mic4dy requested changes

2024-07-17 16:03 UTC, mic4dy commented on lib/view_model/single_page/daily/daily_view_model.dart
> +    }
getLatestDayの仕様修正するならここも比較して矛盾がないように実装する

2024-07-20 03:24 UTC, Atori-Ikeyama commented on lib/view_model/single_page/daily/daily_view_model.dart
> +  Future<void> updateSelectedDay(DateTime selectedDay, {DateTime? focusedDay}) async {
updateSelectedDayっていう関数名なので引数がselected dayだということは自明かなと思ったのと，他のupdateHoge関数の仕様と近づけてみたかったという意図でした．
変える必要はないと思いつつ，逆に変えない方がいい理由ってありましたっけ？

2024-07-20 03:32 UTC, Atori-Ikeyama commented on lib/view_model/single_page/daily/daily_view_model.dart
> +  Future<void> updateSelectedDay(DateTime selectedDay, {DateTime? focusedDay}) async {
selectedDayがnullableである必要がなくなったので，こんな感じにするのはありそう.
```suggestion
  Future<void> updateSelectedDay({required DateTime selectedDay, DateTime? focusedDay}) async {
```

2024-07-20 03:48 UTC, Atori-Ikeyama commented on lib/repository/local/sqlite/menus/menus_local_repository.dart
> +    if (await _count() == 0) return DateTime.now();
確かに，とするとgetLatestUpdateDay()でいいのでgetLatestDay()を実装する必要がなさそうですね．

2024-08-04 07:16 UTC, mic4dy requested changes

2024-08-04 07:16 UTC, mic4dy commented on lib/repository/local/sqlite/menus/menus_local_repository.dart
> -  }
削除する必要はなさそう

2024-08-04 07:16 UTC, mic4dy commented on lib/view_model/single_page/daily/daily_view_model.dart
> +      Flavor.dev => await ref.read(menusLocalRepositoryProvider).getLatestUpdateDay(),
update Dayではなくて給食の最新日の方が適切

2024-08-04 07:16 UTC, mic4dy commented on lib/view_model/single_page/daily/daily_view_model.dart
> +  Future<void> updateSelectedDay({required DateTime selectedDay, DateTime? focusedDay}) async {
カレンダーを選択せずに週だけ周回するときにFocusedDayだけ変更したいと思うけどなんで必須にしたんやろ

2024-08-04 07:16 UTC, mic4dy commented on lib/view_model/single_page/splash/splash_view_model.dart
> +      from: DateTime.now().subtract(const Duration(days: 90)),
３ヶ月は90日ではない

2024-08-04 07:16 UTC, mic4dy commented on lib/view_model/single_page/splash/splash_view_model.dart
> +      updateAt: latestUpdate.add(const Duration(seconds: 1)),
isGreaterThanOrEqualToで見るなら一秒足す必要なさそう

2024-08-06 08:25 UTC, Atori-Ikeyama commented on lib/view_model/single_page/splash/splash_view_model.dart
> +      from: DateTime.now().subtract(const Duration(days: 90)),
Durationはmonthでの指定ができないので，実装の簡便さから90日でいいのかなと思ってました．

2024-08-06 08:32 UTC, Atori-Ikeyama commented on lib/view_model/single_page/daily/daily_view_model.dart
> +  Future<void> updateSelectedDay({required DateTime selectedDay, DateTime? focusedDay}) async {
理解不足だったらすみません．
FocusedDayだけを更新する場合は`updateFocusedDay`を使えばいいのかなと思っていました．
メソッド名が` updateSelectedDay`ということもあり，SelectedDayを更新しない利用は可読性を下げる可能性もあるので必須で良いのかなと...

2024-08-06 08:55 UTC, Atori-Ikeyama commented on lib/view_model/single_page/splash/splash_view_model.dart
> +      from: DateTime.now().subtract(const Duration(days: 90)),
どういう仕様がいいんでしょうか？
個人的には厳密に3ヶ月にする必要はないのかなと思って90日にしてました．
2ヶ月前の1日以降のデータを取得するのがいいですかね？こんな感じで．
```
DateTime _now = DateTime.now();
DateTime result = DateTime(_now.year, _now.month - 2, 1);
```
（8/6にサインアップしたら6/1以降のデータを取得）
今月のデータがあるかどうかで変わっちゃいますが...

2024-08-15 15:45 UTC, tauto1127 approved these changes

2024-08-15 15:48 UTC, merged