feature: 大枠は作った！
Hakondate/Hakondate pull request #241
Opened 2024-08-19 07:03 UTC by Atori-Ikeyama

**Issueリンク**

#

**実装したこと**

- [ ] 

**実装しなかったこと**

- 特になし

**スクリーンショット**

**補足事項**

- 特になし

**チェックリスト**

- [ ] 提出予定のファイルを確認し不要な変更やファイルが混入していないかを確認した
- [ ] 環境変数や秘匿情報を扱うファイルの変更を適切に行なった（または変更していない）
    - [ ] 管理情報の更新を行なった
    - [ ] 該当ファイルを保存場所にアップロードした

2024-10-07 08:32 UTC, tauto1127 requested changes

2024-10-07 08:32 UTC, tauto1127 commented on lib/view_model/multi_page/user/user_view_model.dart
> +  Future<DateTime?> _getSameSchoolAuthorizedAt(int schoolId) async {
Sameっていります？

2024-10-07 08:32 UTC, tauto1127 commented on lib/view/authorization/authorization.dart
SizedBoxのサイズとかsize.dartのconstを使ったほうがいいかもしれないです

2024-10-07 08:39 UTC, Atori-Ikeyama commented on lib/view_model/multi_page/user/user_view_model.dart
> +  Future<DateTime?> _getSameSchoolAuthorizedAt(int schoolId) async {
いらないね．
言い訳をしておくと，同じ学校の別のアカウントがあった時に認証を飛ばす処理を実装しようとしてた名残です...

2024-11-11 09:09 UTC, tauto1127 approved these changes

2024-11-11 09:10 UTC, merged