iosリリースのための諸々設定
Hakondate/Hakondate pull request #243
Opened 2024-08-20 01:52 UTC by tauto1127

**Issueリンク**

#

**実装したこと**

- [ 
- [x] カテゴリをeducationに設定
- [x] iPadを対応端末から除外（対応端末にすると，iPad用のスクショも作成しなきゃいけなくなり手間）
- [x] Xcode16への対応

**実装しなかったこと**

- 特になし

**スクリーンショット**

**補足事項**

- 特になし

**チェックリスト**

- [x] 提出予定のファイルを確認し不要な変更やファイルが混入していないかを確認した
- [x] 環境変数や秘匿情報を扱うファイルの変更を適切に行なった（または変更していない）
    - [x] 管理情報の更新を行なった
    - [x] 該当ファイルを保存場所にアップロードした

2024-08-20 01:55 UTC, tauto1127 commented
pubspecyaml 参考
https://github.com/flutter/flutter/issues/151467

2024-08-24 23:32 UTC, tauto1127 commented on ios/Runner.xcodeproj/project.pbxproj
> +				SUPPORTS_MACCATALYST = NO;
ipad省くため

2024-08-24 23:32 UTC, tauto1127 commented on ios/Runner.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_LSApplicationCategoryType = "public.app-category.education";
カテゴリタイプ

2024-08-24 23:32 UTC, tauto1127 commented on ios/Runner.xcodeproj/project.pbxproj
> +				CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES;
これを指定しないと，xcode16でビルドエラーが起こる(vscodeでは怒らない）

2024-08-24 23:33 UTC, tauto1127 commented on ios/Runner.xcodeproj/project.pbxproj
> +				TARGETED_DEVICE_FAMILY = 1;
iphone向けという意味
https://qiita.com/pugiemonn/items/952eff54bc4aeea2fb1c

2024-08-24 23:35 UTC, tauto1127 commented on pubspec.yaml
> +
https://github.com/flutter/flutter/issues/151467
xcodeでビルドできない問題に対処するために，↑に従って対処しました

2024-08-26 12:20 UTC, mic4dy requested changes

2024-08-30 14:21 UTC, tauto1127 commented on ios/Runner.xcodeproj/project.pbxproj
> +				CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES;
https://github.com/firebase/flutterfire/issues/12962#issuecomment-2183898535
これを参考にしました

2024-09-19 03:07 UTC, tauto1127 commented on ios/Runner.xcodeproj/project.pbxproj
> +				CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES;
xcode 16の正式リリース版でも同じようにビルドエラーが起こりました
同じようなissueが何個も立ってて，それをみてみても同じような解決法ばっかだったのでとりあえずこれでいい気がします

2024-09-19 03:30 UTC, mic4dy approved these changes

2024-09-19 03:50 UTC, merged