ユーザー登録時に本名を受け付けるようにした変更
Hakondate/Hakondate pull request #254
Opened 2024-11-11 07:13 UTC by uwatcha

**Issueリンク**

#

**実装したこと**

- [x] ユーザー登録画面で姓と名の入力欄を設けた
- [x] あだ名に関する注意書き(ヘルプ)を本名用に書き直した
- [x] 内部のDBやstateの変数のnameを、lastNameとfirstNameに変更した

**実装しなかったこと**

- 特になし

**スクリーンショット**

![Simulator Screenshot - iPhone 15 - 2024-11-11 at 16 12 18](https://github.com/user-attachments/assets/03aa8fc2-31dd-4c8e-9edb-c05822a13ffd)

**補足事項**

- 特になし

**チェックリスト**

- [ ] 提出予定のファイルを確認し不要な変更やファイルが混入していないかを確認した
- [ ] 環境変数や秘匿情報を扱うファイルの変更を適切に行なった（または変更していない）
    - [ ] 管理情報の更新を行なった
    - [ ] 該当ファイルを保存場所にアップロードした

2024-11-18 09:36 UTC, Atori-Ikeyama requested changes
一旦コードを見ただけのレビューです

2024-11-18 09:36 UTC, Atori-Ikeyama commented on pubspec.yaml
> +  # build_runner をセーブするたびに自動実行
日本語がちょっと変．
ファイルをセーブするたびにbuild_runnerが自動実行、とかじゃないかな？

2024-11-18 09:36 UTC, Atori-Ikeyama commented on lib/view/splash/splash.dart
> +                        debugPrint(error.toString());
残す必要がなければ消しましょう

2024-11-18 09:36 UTC, Atori-Ikeyama commented on lib/view/component/signing_form/name_form.dart
> +                          '　原則，本名を入力してください．また，あとで変更することもできます．\n'
・「原則」って言葉いるかな？
・「本名」よりも，「お子様の名前」か「お子様の本名」とかの方が何を入れたらいいかわかりやすいかも

2024-11-18 09:36 UTC, Atori-Ikeyama commented on lib/repository/local/sqlite/users/users_local_repository.dart
> +    /*あとで戻す*/ UsersSchema? usersSchema;
不要なコメントは消しましょ

2024-11-18 12:41 UTC, uwatcha commented on pubspec.yaml
> +  # build_runner をセーブするたびに自動実行
修正

2024-11-18 12:41 UTC, uwatcha commented on lib/view/splash/splash.dart
> +                        debugPrint(error.toString());
修正

2024-11-18 12:43 UTC, uwatcha commented on lib/view/component/signing_form/name_form.dart
> +                          '　原則，本名を入力してください．また，あとで変更することもできます．\n'
修正

2024-11-18 12:43 UTC, uwatcha commented on lib/repository/local/sqlite/users/users_local_repository.dart
> +    /*あとで戻す*/ UsersSchema? usersSchema;
修正

2024-11-25 07:44 UTC, tauto1127 commented on lib/view/component/signing_form/name_form.dart
> +                      maxLength: 5,
maxLength

2024-11-25 09:19 UTC, Atori-Ikeyama approved these changes
LGTM

2024-11-25 09:21 UTC, merged