インフォメーション画面
Hakondate/Hakondate pull request #99
Opened 2023-02-19 09:07 UTC by uwatcha

**Issueリンク**

#

**実装したこと**

- hoge

**実装しなかったこと**

- 特になし

**スクリーンショット**

**補足事項**

- 特になし

**セルフレビュー**

- [ ] コーディング規約に沿ったコードを書いた
    - ファイル末尾の改行
    - Widgetの階層構造
    - 静的型付け
    くらいは少なくとも確認する
- [ ] 提出予定のファイルを確認し不要な変更やファイルが混入していないかを確認した

2023-08-07 08:55 UTC, mic4dy reviewed
今回のメイン実装以外の部分だけ見てコメントしておきます。
メイン実装部分はちゃんとPRが発行された時点でみます〜。

2023-08-07 08:55 UTC, mic4dy commented on android/app/src/main/AndroidManifest.xml
> +    </queries>
必要最小限の変更のみ加える（ほとんどいらんと思う）

2023-08-07 08:55 UTC, mic4dy commented on android/app/build.gradle
> +    throw new FileNotFoundException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
ここの変更は必要？

2023-08-07 08:55 UTC, mic4dy commented on assets/images/help/graphFormula.png
Helpのものは削除（別タスクで実装しているため）

2023-08-07 08:55 UTC, mic4dy commented on assets/images/help/juniorSLIS.png
Helpのものは削除（別タスクで実装しているため）

2023-08-07 08:55 UTC, mic4dy commented on assets/images/help/juniorZinc.png
Helpのものは削除（別タスクで実装しているため）

2023-08-07 08:55 UTC, mic4dy commented on assets/images/help/registeredInfo.png
Helpのものは削除（別タスクで実装しているため）

2023-08-07 08:55 UTC, mic4dy commented on assets/images/help/listToMenu.png
Helpのものは削除（別タスクで実装しているため）

2023-08-07 08:55 UTC, mic4dy commented on lib/router/routes.dart
> +      //'/home/help': (_) => const MaterialPage<dynamic>(child: Help()),
今回の対象ではないので元に戻す

2023-08-07 08:55 UTC, mic4dy commented on lib/view/help/help_content_column.dart
Helpのものは削除（別タスクで実装しているため）

2023-08-07 08:55 UTC, mic4dy commented on lib/view/help/help.dart
Helpのものは削除（別タスクで実装しているため）

2023-08-07 12:19 UTC, AkariKokuba commented
テキストの大きさ、配置を変更。現在協力していただいている学校を「現在協力校なし」に変更

2023-08-13 08:04 UTC, uwatcha commented
- [ ] AndroidManifest.xmlの不要な追加を削除
- [ ] build.gradleのFileNotFoundExceptionをGradleExceptionに戻す
- [ ] Help関連のアセットやファイルを削除
- [ ] routes.dartの変更を戻す

2023-08-14 11:41 UTC, mic4dy requested changes

2023-08-14 11:41 UTC, mic4dy commented on lib/view/component/sentence/linked_annotation.dart
> +    final String url;
インデントは揃える
```suggestion
  });

  final String text;
  final String url;
```

2023-08-14 11:41 UTC, mic4dy commented on lib/view/component/sentence/linked_annotation.dart
> +        children: [
`// ignore: ~~~~` はlinterを無視するという文句なので避ける
```suggestion
        children: <Widget>[
```

2023-08-14 11:41 UTC, mic4dy commented on lib/view/component/sentence/linked_annotation.dart
> +  const LinkedAnnotation ({
`Annotation` はあまり見ない

2023-08-14 11:41 UTC, mic4dy commented on lib/view/component/sentence/linked_annotation.dart
> +      },
ViewModelに実装する

2023-08-14 11:41 UTC, mic4dy commented on lib/view/component/sentence/linked_annotation.dart
> +        children: [
Columnで囲う必要はない
Padding（Margin）つけたいならPaddingWidgetを使えば良い

2023-08-14 11:41 UTC, mic4dy commented on lib/view/component/sentence/linked_annotation.dart
> +            width: double.infinity,
これも不要
右寄せで配置したいなら `AlignWidget` を使うべき

2023-08-14 11:41 UTC, mic4dy commented on lib/view/component/sentence/linked_sentence.dart
> +    final String url;
```suggestion
    super.key,
  });

  final String text;
  final String url;
```

2023-08-14 11:41 UTC, mic4dy commented on lib/view/component/sentence/linked_sentence.dart
> +  const LinkedSentence ({
`LinkedAnnotation` と結合できる

2023-08-14 11:41 UTC, mic4dy commented on lib/view/component/sentence/padded_sentence.dart
> +      children: [
`// ignore:` は使わない

2023-08-14 11:41 UTC, mic4dy commented on lib/view/component/sentence/padded_sentence.dart
> +    final String text;
インデント

2023-08-14 11:41 UTC, mic4dy commented on lib/view/component/sentence/padded_sentence.dart
> +  const PaddedSentence ({
命名をもうちょいわかりやすく
このくらいならクラス化しなくてもいいかもしれない

2023-08-14 11:41 UTC, mic4dy commented on lib/view/component/sentence/padded_sentence.dart
> +      crossAxisAlignment: CrossAxisAlignment.start,
ここもColumn使わなくても実装できる

2023-08-14 11:41 UTC, mic4dy commented on lib/view/component/sentence/square_and_headline.dart
他と結合できる

2023-08-14 11:41 UTC, mic4dy commented on lib/view/component/sentence/underlined_sentence.dart
ここも結合できる

2023-08-14 11:41 UTC, mic4dy commented on lib/view/information/information_content_column.dart
`lib/view/information/information.dart` に結合可能

2023-08-14 11:41 UTC, mic4dy commented on pubspec.yaml
> +  webview_flutter: ^4.0.7
```suggestion

```

2023-08-14 13:40 UTC, mic4dy commented
```
git stash
git switvh feature/information
git pull
```

2023-08-21 16:34 UTC, mic4dy reviewed
微修正だけよろみ〜〜〜

2023-08-22 01:39 UTC, mic4dy commented on pubspec.yaml
> +  webview_flutter: ^4.0.7
これ使ってなさそう？

2023-09-11 12:33 UTC, mic4dy approved these changes
![LGTM](https://images.lgtmgen.org/4af95bbb-e8f2-4db2-9ab4-3ad2b4d8f0a0)

2023-09-11 12:37 UTC, merged